/**
 * Everything about THIS practice and THIS equipment, in one place.
 *
 * The app is built for Apex Dental and that is the priority — but four
 * values were scattered inline across services, composables and templates,
 * and every one of them is wrong the moment the monitor is replaced or the
 * app is set up for a second office:
 *
 *   - the Open Dental commlog definition and image-category numbers, which
 *     are created per-practice and mean nothing anywhere else;
 *   - the provider named in the chart-note attribution;
 *   - the monitor whose printout the note points a reader at.
 *
 * Collecting them costs nothing now and turns "swap the monitor" or "set up
 * the second office" into editing this file, rather than grepping for a
 * hospital's worth of string literals. Deliberately NOT a settings screen or
 * a multi-tenant system: there is one site today, and inventing tenancy for
 * a second one that does not exist yet would be the more expensive mistake.
 *
 * To add a site: define another `SiteProfile` below and point `ACTIVE_SITE`
 * at it. Nothing else in the app should hold a practice- or device-specific
 * literal.
 */

/**
 * The physiological monitor whose trace is the real monitoring record.
 *
 * The app's note transcribes moments; the monitor prints a continuous trace
 * for the whole case. The note has to name the device and say where its
 * output ends up, so a reader knows the evidence exists and where to find
 * it — which is device-specific by definition.
 */
export interface MonitorProfile {
  /** As printed on the note and on the Phase 4 attestation. */
  readonly name: string;
  /**
   * Where the trace ends up. `scanned` means a human scans the strip into
   * the patient's chart; `uploaded` means the monitor files it itself, which
   * would let the app verify rather than merely assert.
   */
  readonly traceDelivery: 'scanned' | 'uploaded';
}

/**
 * Practice-specific Open Dental identifiers.
 *
 * These are definition rows created inside one practice's database. They are
 * not Open Dental defaults and they do not transfer: another office's
 * "Sedation Note" commlog type will be a different number, and filing under
 * the wrong one is not reversible through the API.
 */
export interface OpenDentalProfile {
  /** Commlog definition for a sedation note. */
  readonly commTypeSedationNote: number;
  /** Image category the note PDF is filed into. */
  readonly docCategorySedation: number;
}

export interface SiteProfile {
  /** Human name, for anywhere the practice is identified outside the note. */
  readonly practice: string;
  readonly monitor: MonitorProfile;
  readonly openDental: OpenDentalProfile;
  /**
   * The line prepended to the chart note.
   *
   * API writes are force-zeroed to UserNum 0, so Open Dental shows no author
   * — attribution has to live inside the text. Takes the provider from the
   * case rather than a fixed name, so a covering or locum dentist is
   * attributed correctly instead of the practice owner.
   */
  readonly noteAttribution: (provider: string) => string;
}

export const APEX_DENTAL: SiteProfile = {
  practice: 'Apex Dental',
  monitor: {
    name: 'Edan X10',
    traceDelivery: 'scanned',
  },
  openDental: {
    // Created and confirmed inside this practice's Open Dental on
    // 2026-08-14. Never guess these for another site — read them from that
    // site's definition table.
    commTypeSedationNote: 711,
    docCategorySedation: 136,
  },
  noteAttribution: (provider) =>
    `Sedation note generated by Sedation Pro and sent to chart by ${provider.trim() || 'the treating provider'}.`,
};

/** The site this build serves. */
export const ACTIVE_SITE: SiteProfile = APEX_DENTAL;

/**
 * How the note describes where the monitor's trace ended up. Phrased from
 * the profile so replacing the monitor — or moving to one that files its own
 * output — changes the sentence without touching the note builder.
 */
export function monitorTraceDescription(site: SiteProfile = ACTIVE_SITE): string {
  return site.monitor.traceDelivery === 'uploaded'
    ? `${site.monitor.name} trace uploaded to the patient chart`
    : `${site.monitor.name} printout scanned into the patient chart`;
}

/** Label for the Phase 4 attestation, likewise device-derived. */
export function monitorAttestationLabel(site: SiteProfile = ACTIVE_SITE): string {
  return site.monitor.traceDelivery === 'uploaded'
    ? `Pulse-ox trace (${site.monitor.name}) uploaded to chart`
    : `Pulse-ox printout (${site.monitor.name}) scanned to chart`;
}
