import { computed, ref, type ComputedRef, type Ref } from 'vue';

import { clinicalNoteToPdf } from './clinicalNoteToPdf';
import { clinicalNoteToText } from './clinicalNoteText';
import { chartDisplayName } from './chartHistory';
import type { ClinicalNote } from './useClinicalNote';
import { readCredentials } from '@/services/od-credentials';
import {
  bytesToBase64,
  describeOdError,
  getPatient,
  isOdError,
  postCommlog,
  uploadDocument,
  type OdPatient,
} from '@/services/opendental';
import { usePatientStore } from '@/stores/patient';
import { useChartSendStore, type ArtifactKind } from '@/stores/chart-send';

/**
 * "Send to chart" — files the clinical note into Open Dental as a commlog
 * (the text) and a document (the PDF).
 *
 * Everything here is shaped by one fact: **both writes are permanent.**
 * Commlogs have no DELETE, and document deletion fails at this practice. So
 * the two artifacts are tracked separately, a succeeded one is never resent
 * by the retry path, and the confirmation dialog leads with the patient's
 * name rather than the number the user typed.
 */

/**
 * API writes are force-zeroed to UserNum 0, so the commlog shows no author in
 * Open Dental. Attribution has to live inside the text itself.
 */
const ATTRIBUTION = 'Sedation note generated by Sedation Pro and sent to chart by Dr. Hassan.';

/** The API allows 1 req/sec; a little headroom keeps a burst off a 429. */
export const RATE_LIMIT_SPACING_MS = 1100;

export interface SendPrecondition {
  readonly ready: boolean;
  /** Why the button is disabled, shown inline. Empty when ready. */
  readonly reason: string;
  /** True when the fix is entering API keys, so the UI can link to Settings. */
  readonly needsSettings: boolean;
}

export interface ConfirmTarget {
  readonly patNum: number;
  readonly name: string;
  readonly birthdate: string;
  /** Artifacts this send would actually write — never includes a sent one. */
  readonly artifacts: ReadonlyArray<ArtifactKind>;
}

export type ResultTone = 'ok' | 'partial' | 'fail';

export interface ResultLine {
  readonly tone: ResultTone;
  readonly text: string;
}

const sleep = (ms: number): Promise<void> => new Promise((resolve) => setTimeout(resolve, ms));

/**
 * Is the chart resolved now the same one the case was opened against?
 *
 * Compares the PatNum and the name. The number alone is not enough: charts
 * get merged and re-pointed in a PMS, and a number that now belongs to
 * someone else is exactly the case worth catching. Birthdate is deliberately
 * excluded — it gets corrected in charts, and a corrected DOB is not a
 * different patient.
 */
function sameChart(
  startOfCase: { patNum: number; lName: string; fName: string },
  patNum: number,
  found: { LName: string; FName: string },
): boolean {
  if (startOfCase.patNum !== patNum) return false;
  const norm = (s: string): string => s.trim().toLowerCase();
  return (
    norm(startOfCase.lName) === norm(found.LName) && norm(startOfCase.fName) === norm(found.FName)
  );
}

function fmtTime(iso: string): string {
  const d = new Date(iso);
  return Number.isNaN(d.getTime())
    ? iso
    : d.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' });
}

export interface UseSendToChart {
  readonly precondition: ComputedRef<SendPrecondition>;
  readonly confirmTarget: Ref<ConfirmTarget | null>;
  readonly busy: Ref<boolean>;
  readonly lookupError: Ref<string>;
  readonly resultLines: ComputedRef<ReadonlyArray<ResultLine>>;
  readonly primaryLabel: ComputedRef<string>;
  readonly canResend: ComputedRef<boolean>;
  requestSend: () => Promise<void>;
  requestResend: () => Promise<void>;
  confirmSend: () => Promise<void>;
  cancelSend: () => void;
}

export function useSendToChart(
  note: Ref<ClinicalNote> | ComputedRef<ClinicalNote>,
): UseSendToChart {
  const patient = usePatientStore();
  const send = useChartSendStore();

  const busy = ref(false);
  const lookupError = ref('');
  const confirmTarget = ref<ConfirmTarget | null>(null);
  /** Set when the provider deliberately re-sends an already-filed artifact. */
  const resending = ref(false);

  const parsedMrn = computed<number | null>(() => {
    const raw = patient.mrn.trim();
    if (raw === '') return null;
    const n = Number(raw);
    return Number.isInteger(n) && n > 0 ? n : null;
  });

  const precondition = computed<SendPrecondition>(() => {
    if (readCredentials() === null) {
      return {
        ready: false,
        reason: 'Open Dental is not connected on this device.',
        needsSettings: true,
      };
    }
    if (parsedMrn.value === null) {
      return {
        ready: false,
        reason:
          patient.mrn.trim() === ''
            ? 'Add the patient ID to the MRN field in Phase 1.'
            : 'MRN must be the Open Dental patient number — digits only.',
        needsSettings: false,
      };
    }
    if (send.patientMismatch(patient.mrn)) {
      return {
        ready: false,
        reason: `Already sent for patient ${send.patNum ?? '—'}. The MRN has changed since — check Open Dental before sending again.`,
        needsSettings: false,
      };
    }
    if (send.allSent) {
      return {
        ready: false,
        reason: 'Note text and PDF are already in the chart.',
        needsSettings: false,
      };
    }
    return { ready: true, reason: '', needsSettings: false };
  });

  const primaryLabel = computed(() => {
    const pending = send.pendingArtifacts;
    if (pending.length === 2) return 'Send to chart';
    if (pending.length === 0) return 'Sent to chart';
    return pending[0] === 'pdf' ? 'Retry PDF only' : 'Retry note text only';
  });

  /** Re-sending something already filed is possible, but never the primary. */
  const canResend = computed(() => send.anythingSent && precondition.value.needsSettings === false);

  // -------- Lookup + confirm ------------------------------------------------

  async function openConfirm(artifacts: ReadonlyArray<ArtifactKind>): Promise<void> {
    const creds = readCredentials();
    const patNum = parsedMrn.value;
    if (creds === null || patNum === null || artifacts.length === 0) return;

    busy.value = true;
    lookupError.value = '';
    try {
      // The wrong-patient guard. A mistyped MRN must fail HERE, while the
      // mistake is still reversible — not at write time, when it isn't.
      const found: OdPatient = await getPatient(patNum, creds);

      // Hard stop, and the only one in this feature. Everything about the
      // Phase 1 chart lookup is advisory, but this is different: the case was
      // opened against a chart that was confirmed at the start, and the chart
      // the note is about to be filed into is a different one. That is the
      // wrong-patient scenario, not a stale field, so it refuses rather than
      // warns. The escape hatch is deliberate — fix the MRN, or reset the
      // send record — never a button that shrugs and writes anyway.
      const startOfCase = patient.resolvedIdentity;
      if (startOfCase !== null && !sameChart(startOfCase, patNum, found)) {
        confirmTarget.value = null;
        lookupError.value =
          `This case was started against ${chartDisplayName(startOfCase.lName, startOfCase.fName)} ` +
          `(ID ${startOfCase.patNum}), but ID ${patNum} is ` +
          `${chartDisplayName(found.LName, found.FName)}. The MRN changed during the case — ` +
          'nothing has been written. Check which chart this note belongs to before sending.';
        return;
      }

      confirmTarget.value = {
        patNum,
        name: chartDisplayName(found.LName, found.FName),
        birthdate: found.Birthdate,
        artifacts,
      };
    } catch (error) {
      confirmTarget.value = null;
      lookupError.value = isOdError(error)
        ? error.kind === 'http' && error.status === 404
          ? `No patient found for ID ${patNum}. Check the MRN field.`
          : describeOdError(error)
        : `Could not look up patient ${patNum}.`;
    } finally {
      busy.value = false;
    }
  }

  async function requestSend(): Promise<void> {
    resending.value = false;
    if (!precondition.value.ready) return;
    await openConfirm(send.pendingArtifacts);
  }

  /** Deliberate second copy — the caller gates this behind its own warning. */
  async function requestResend(): Promise<void> {
    resending.value = true;
    if (readCredentials() === null || parsedMrn.value === null) return;
    await openConfirm(['commlog', 'pdf']);
  }

  function cancelSend(): void {
    confirmTarget.value = null;
    resending.value = false;
  }

  // -------- Write -----------------------------------------------------------

  async function confirmSend(): Promise<void> {
    const target = confirmTarget.value;
    const creds = readCredentials();
    if (target === null || creds === null) return;

    confirmTarget.value = null;
    busy.value = true;

    try {
      if (
        !resending.value &&
        !send.bindPatient(target.patNum, `${target.name} · ${target.birthdate}`)
      ) {
        lookupError.value =
          'This case already has a send record for a different patient. Review Open Dental, then reset the send record.';
        return;
      }

      const wantsCommlog = target.artifacts.includes('commlog');
      const wantsPdf = target.artifacts.includes('pdf');
      let wrote = false;

      if (wantsCommlog) {
        // On a deliberate resend the artifact is already 'sent' and frozen, so
        // the state transitions are skipped — the write itself still happens.
        send.markCommlogSending();
        try {
          await postCommlog(
            { patNum: target.patNum, note: `${ATTRIBUTION}\n\n${clinicalNoteToText(note.value)}` },
            creds,
          );
          send.markCommlogSent();
        } catch (error) {
          send.markCommlogFailed(
            isOdError(error) ? describeOdError(error) : 'The note text failed to send.',
          );
        }
        wrote = true;
      }

      if (wantsPdf) {
        if (wrote) await sleep(RATE_LIMIT_SPACING_MS);
        send.markPdfSending();
        try {
          const bytes = await clinicalNoteToPdf(note.value);
          await uploadDocument(
            {
              patNum: target.patNum,
              rawBase64: bytesToBase64(bytes),
              description: `Sedation note · ${note.value.header.date}`,
              dateCreated: new Date().toISOString().slice(0, 10),
            },
            creds,
          );
          send.markPdfSent();
        } catch (error) {
          send.markPdfFailed(
            isOdError(error) ? describeOdError(error) : 'The PDF could not be generated or sent.',
          );
        }
      }
    } finally {
      busy.value = false;
      resending.value = false;
    }
  }

  // -------- Reporting -------------------------------------------------------

  /**
   * One line per artifact, naming which one, its HTTP status, and — the part
   * the operator actually needs — whether anything reached the chart, since
   * that decides whether they have to go clean something up in Open Dental.
   */
  const resultLines = computed<ReadonlyArray<ResultLine>>(() => {
    const lines: ResultLine[] = [];
    const who = send.patientLabel ?? 'the patient';

    const describe = (kind: ArtifactKind, label: string): void => {
      const state = kind === 'commlog' ? send.commlog : send.pdf;
      if (state.status === 'sent') {
        lines.push({ tone: 'ok', text: `${label} written to the chart at ${fmtTime(state.at)}.` });
      } else if (state.status === 'failed') {
        lines.push({ tone: 'fail', text: `${label} failed — ${state.detail}` });
      } else if (state.status === 'sending') {
        lines.push({ tone: 'partial', text: `${label} — send interrupted, outcome unknown.` });
      }
    };

    describe('commlog', 'Note text');
    describe('pdf', 'PDF');

    if (lines.length === 0) return lines;

    if (send.allSent) {
      return [{ tone: 'ok', text: `Sent to chart · note text and PDF written to ${who}.` }];
    }
    if (send.anythingSent) {
      lines.push({
        tone: 'partial',
        text: 'Part of this note is already in the chart. Retry only what failed — resending everything files a second copy that cannot be removed.',
      });
      return lines;
    }

    // An artifact still reading 'sending' was interrupted mid-write, and the
    // app cannot know whether it landed. Claiming "nothing was written" there
    // would be the one wrong thing to say: it invites the retry that
    // duplicates. Only assert it when every artifact definitively failed.
    const outcomeUnknown = send.commlog.status === 'sending' || send.pdf.status === 'sending';
    if (!outcomeUnknown) {
      lines.push({ tone: 'fail', text: 'Nothing was written to the chart.' });
    }
    return lines;
  });

  return {
    precondition,
    confirmTarget,
    busy,
    lookupError,
    resultLines,
    primaryLabel,
    canResend,
    requestSend,
    requestResend,
    confirmSend,
    cancelSend,
  };
}
